### ISSUE TITLE
prefer an enum (i.e. constants) over strings when referring to a pre-defined set of values

### ISSUE THREAD

**Issue by reefloretto** [omar-nema/blackbox-native#3]
https://github.com/omar-nema/blackbox-native/blob/c478ce6c84af0eda23102a93715c299883baeee0/App.js#L51

**Comment by reefloretto** [comment]
additional detail: you'd probably want to have a file called `audioStates` (or something similar) which exports an object that looks like:
```
export const audioStates = {
  INIT: "INIT",
  PAUSE: "PAUSE",
  PLAY: "PLAY",
  ...
}
```
the benefit of this would be to have a single source of truth for the various audio states

**Comment by omar-nema** [comment]
Makes perfect sense. Setting a state via text is hacky.
