### ISSUE TITLE
turn anonymous async functions into named functions and then call them as needed

### ISSUE THREAD

**Issue by reefloretto** [omar-nema/blackbox-native#4]
https://github.com/omar-nema/blackbox-native/blob/c478ce6c84af0eda23102a93715c299883baeee0/App.js#L65

mostly motivated by the [single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle); i.e. `componentDidMount` should know _that_ fonts need to be loaded but it should _not_ know which specific fonts to know (and what their source paths are)

**Comment by omar-nema** [comment]
Hm okay. Had always thought - something should go in a separate function only if it's repeated. I'll read more about this.

**Comment by omar-nema** [comment]
The idea here is to make debugging easier - is this right? And maybe more readable too?

**Comment by reefloretto** [comment]
yeah, both those improvements are true: debugging is easier / code is more modular & readable. it is also true that encapsulating non-repeated code can be a premature optimization but i usually err on the side of readability in these scenarios (at least i try 😅)
