### ISSUE TITLE
possible for state to represent initializations prematurely

### ISSUE THREAD

**Issue by reefloretto** [omar-nema/blackbox-native#5]
i _think_ it would be possible for this line to execute before the `await` functions finish running; this may cause the state to misleadingly say that initialization has occurred successfully even if there were errors during the execution of either `initializeRecording` or `askForPermissions`. to demonstrate this:

```js
// from inside node REPL environment
> const yoooo = async () => {
... await setTimeout(() => { console.log("yo from inside await") }, 5000)
... console.log("yo from outside await")
... }
> yoooo()
yo from outside await // i think you want this to run second
yo from inside await // i think you want this to run first
```

https://github.com/omar-nema/blackbox-native/blob/c478ce6c84af0eda23102a93715c299883baeee0/App.js#L75

**Comment by omar-nema** [comment]
Makes perfect sense - thank you! I'll fix this.

**Comment by omar-nema** [comment]
So I should say 'await  this.setState({ recordingLoaded: true})'?

**Comment by reefloretto** [comment]
> So I should say 'await this.setState({ recordingLoaded: true})'?

hmm -- i might actually make `#initializeRecording` return a `Promise` and then call `setState({ recordingLoaded: true })` _after_ that promise resolves. if that makes sense? because i think with `await this.setState(...)` you'd run into the same issue where the call to `setState` can occur _before_ the `initializeRecording` async function is finished
